-- ============================================================
-- SCRIPT DE RÉINITIALISATION DES DONNÉES
-- Vide toutes les tables du projet Oracle Fitness
-- Connexion : ADMIN_FITNESS
-- ============================================================

PROMPT ======= RÉINITIALISATION DES DONNÉES =======

-- Désactivation temporaire des contraintes FK
ALTER TABLE DETAILS_EXERCICE_SEANCE DISABLE CONSTRAINT fk_details_session;
ALTER TABLE DETAILS_EXERCICE_SEANCE DISABLE CONSTRAINT fk_details_exercise;

ALTER TABLE SEANCE_ENTRAINEMENT DISABLE CONSTRAINT fk_seance_user;

ALTER TABLE SUIVI_ALIMENTAIRE DISABLE CONSTRAINT fk_suivi_user;
ALTER TABLE SUIVI_ALIMENTAIRE DISABLE CONSTRAINT fk_suivi_meal;

-- Suppression de toutes les données
DELETE FROM DETAILS_EXERCICE_SEANCE;
DELETE FROM SUIVI_ALIMENTAIRE;
DELETE FROM REPAS;
DELETE FROM SEANCE_ENTRAINEMENT;
DELETE FROM EXERCICE;
DELETE FROM "USER";

COMMIT;

-- Réactivation des contraintes FK
ALTER TABLE DETAILS_EXERCICE_SEANCE ENABLE CONSTRAINT fk_details_session;
ALTER TABLE DETAILS_EXERCICE_SEANCE ENABLE CONSTRAINT fk_details_exercise;

ALTER TABLE SEANCE_ENTRAINEMENT ENABLE CONSTRAINT fk_seance_user;

ALTER TABLE SUIVI_ALIMENTAIRE ENABLE CONSTRAINT fk_suivi_user;
ALTER TABLE SUIVI_ALIMENTAIRE ENABLE CONSTRAINT fk_suivi_meal;

PROMPT ======= RÉINITIALISATION TERMINÉE =======
